on: [push]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    -uses: actions/checkout@v2
    -name: run the action
     id: test
     uses: ./
     with:
       myinput: 'change input to current'
    -name:  output
     run: |
       echo ${{ steps.test.outputs.memory }}
       echo "current total memory in current env"
       
