on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    name: actions in workflow
    steps:
    - name: run the checkout action
      uses: actions/checkout@v2
    - name: step 2
      id: test
      uses: ./
      with:
       myinput: 'change input to current'
    - name:  output
      run: |
        echo ${{ steps.test.outputs.memory }}
        echo "current total memory in current env"
       
