on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    name: job 1 in workflow
    steps:
    - name: stage 1 (run the checkout action)
      uses: actions/checkout@v2
    - name: stage 2 (Building docker image)
      id: test
      uses: ./
      with:
       myInput: '--------'
    - name: stage 3 (provide outputs)
      run: |
        echo ${{ steps.test.outputs.memory }}
        echo "current total memory in current env"
        echo ${{ steps.test.outputs.check_status1 }}
        echo "check_status1 in current env"
        echo ${{ steps.test.outputs.check_status2 }}
        echo "check_status2 in current env"
        
  second-job:
    runs-on: ubuntu-latest
    name: job 2 in workflow the same steps
    steps:
    - name: stage 1 (run the checkout action)
      uses: actions/checkout@v2
    - name: stage 2 (Building docker image)
      id: test
      uses: ./
      with:
       myInput: 'end the stage 2'
    - name: stage 3 (provide outputs)
      run: |
        echo ${{ steps.test.outputs.memory }}
        echo "current total memory in current env"
       
