on: [push]

jobs:
  first-job:
    runs-on: ubuntu-latest
    name: actions in workflow
    steps:
    - name: stage 1 (run the checkout action)
      uses: actions/checkout@v2
    - name: stage 2 (Building docker image)
      id: test
      uses: ./
      with:
       myInput: 'change input to newOne'
    - name: stage 3 (provide outputs)
      run: |
        echo ${{ steps.test.outputs.memory }}
        echo "current total memory in current env"
       
